"use strict";
/**
 * Leekwars
 * Leekwars backend api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Aicode = void 0;
/**
* AI code
*/
class Aicode {
    'id';
    /**
    * timestamp
    */
    'modified';
    'code';
    static discriminator = undefined;
    static attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "modified",
            "baseName": "modified",
            "type": "number"
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        }
    ];
    static getAttributeTypeMap() {
        return Aicode.attributeTypeMap;
    }
}
exports.Aicode = Aicode;
