"use strict";
/**
 * Leekwars
 * Leekwars backend api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AiCreateRequest = void 0;
class AiCreateRequest {
    'folderId';
    'name';
    /**
    * Leekscript version
    */
    'version';
    static discriminator = undefined;
    static attributeTypeMap = [
        {
            "name": "folderId",
            "baseName": "folder_id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "number"
        }
    ];
    static getAttributeTypeMap() {
        return AiCreateRequest.attributeTypeMap;
    }
}
exports.AiCreateRequest = AiCreateRequest;
