"use strict";
/**
 * Leekwars
 * Leekwars backend api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AiCreate200Response = void 0;
class AiCreate200Response {
    'id';
    'name';
    'level';
    'code';
    'folder';
    static discriminator = undefined;
    static attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "number"
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "folder",
            "baseName": "folder",
            "type": "number"
        }
    ];
    static getAttributeTypeMap() {
        return AiCreate200Response.attributeTypeMap;
    }
}
exports.AiCreate200Response = AiCreate200Response;
