"use strict";
/**
 * Leekwars
 * Leekwars backend api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AiFetchRequest = void 0;
class AiFetchRequest {
    /**
    * json string of ai_id mapped by timestamp
    */
    'ais';
    static discriminator = undefined;
    static attributeTypeMap = [
        {
            "name": "ais",
            "baseName": "ais",
            "type": "string"
        }
    ];
    static getAttributeTypeMap() {
        return AiFetchRequest.attributeTypeMap;
    }
}
exports.AiFetchRequest = AiFetchRequest;
