"use strict";
/**
 * Leekwars
 * Leekwars backend api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AiSaveRequest = void 0;
class AiSaveRequest {
    'aiId';
    'code';
    static discriminator = undefined;
    static attributeTypeMap = [
        {
            "name": "aiId",
            "baseName": "ai_id",
            "type": "number"
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        }
    ];
    static getAttributeTypeMap() {
        return AiSaveRequest.attributeTypeMap;
    }
}
exports.AiSaveRequest = AiSaveRequest;
