"use strict";
/**
 * Leekwars
 * Leekwars backend api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AiSave200Response = void 0;
class AiSave200Response {
    /**
    * timestamp
    */
    'modified';
    static discriminator = undefined;
    static attributeTypeMap = [
        {
            "name": "modified",
            "baseName": "modified",
            "type": "number"
        }
    ];
    static getAttributeTypeMap() {
        return AiSave200Response.attributeTypeMap;
    }
}
exports.AiSave200Response = AiSave200Response;
