/**
 * Leekwars
 * Leekwars backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Ai } from './ai';

/**
* AI Tree
*/
export class AiTree {
    'files'?: Array<Ai>;
    'folders': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "files",
            "baseName": "files",
            "type": "Array<Ai>"
        },
        {
            "name": "folders",
            "baseName": "folders",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return AiTree.attributeTypeMap;
    }
}

