/**
 * Leekwars
 * Leekwars backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CreateFile200ResponseAi } from './createFile200ResponseAi';

export class CreateFile200Response {
    'ai': CreateFile200ResponseAi;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ai",
            "baseName": "ai",
            "type": "CreateFile200ResponseAi"
        }    ];

    static getAttributeTypeMap() {
        return CreateFile200Response.attributeTypeMap;
    }
}

