"use strict";
/**
 * Leekwars
 * Leekwars backend api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Credentials = void 0;
/**
* Login credentials
*/
class Credentials {
    'login';
    'password';
    'keepConnected';
    static discriminator = undefined;
    static attributeTypeMap = [
        {
            "name": "login",
            "baseName": "login",
            "type": "string"
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string"
        },
        {
            "name": "keepConnected",
            "baseName": "keep_connected",
            "type": "boolean"
        }
    ];
    static getAttributeTypeMap() {
        return Credentials.attributeTypeMap;
    }
}
exports.Credentials = Credentials;
