/**
 * Leekwars
 * Leekwars backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Login credentials
*/
export class Credentials {
    'login'?: string;
    'password'?: string;
    'keepConnected'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "login",
            "baseName": "login",
            "type": "string"
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string"
        },
        {
            "name": "keepConnected",
            "baseName": "keep_connected",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return Credentials.attributeTypeMap;
    }
}

