/**
 * Leekwars
 * Leekwars backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class EquipWeaponRequest {
    'leekId'?: number;
    'weaponId'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "leekId",
            "baseName": "leek_id",
            "type": "number"
        },
        {
            "name": "weaponId",
            "baseName": "weapon_id",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return EquipWeaponRequest.attributeTypeMap;
    }
}

