/**
 * Leekwars
 * Leekwars backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Farmer opponent
*/
export class FarmerOpponent {
    'id': number;
    'name': string;
    'avatarChanged': number;
    'talent': number;
    'totalLevel': number;
    'leekCount': number;
    'country': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "avatarChanged",
            "baseName": "avatar_changed",
            "type": "number"
        },
        {
            "name": "talent",
            "baseName": "talent",
            "type": "number"
        },
        {
            "name": "totalLevel",
            "baseName": "total_level",
            "type": "number"
        },
        {
            "name": "leekCount",
            "baseName": "leek_count",
            "type": "number"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return FarmerOpponent.attributeTypeMap;
    }
}

