"use strict";
/**
 * Leekwars
 * Leekwars backend api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Farmer = void 0;
/**
* Farmer
*/
class Farmer {
    'id';
    'login';
    'name';
    'talent';
    'victories';
    'draws';
    'defeats';
    'connected';
    'admin';
    'moderator';
    'banned';
    'inGarden';
    'verified';
    'wonSoloTournaments';
    'wonFarmerTournaments';
    'wonTeamTournaments';
    'wonBattleRoyale';
    'totalLevel';
    'leekCount';
    'fights';
    'teamFights';
    'trophies';
    'points';
    'ranking';
    'godsonsLevel';
    'habs';
    'crystals';
    'team';
    /**
    * Weapons list
    */
    'weapons';
    /**
    * Chips list
    */
    'chips';
    /**
    * Potions list
    */
    'potions';
    /**
    * Hats list
    */
    'hats';
    /**
    * Resources list
    */
    'resources';
    /**
    * Component list
    */
    'components';
    /**
    * Component recipe list
    */
    'schemes';
    /**
    * Some item list ???
    */
    'pomps';
    /**
    * Leeks by id
    */
    'leeks';
    /**
    * Associated IA for each leek id
    */
    'leekAis';
    'folders';
    /**
    * List of ai
    */
    'ais';
    static discriminator = undefined;
    static attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "login",
            "baseName": "login",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "talent",
            "baseName": "talent",
            "type": "number"
        },
        {
            "name": "victories",
            "baseName": "victories",
            "type": "number"
        },
        {
            "name": "draws",
            "baseName": "draws",
            "type": "number"
        },
        {
            "name": "defeats",
            "baseName": "defeats",
            "type": "number"
        },
        {
            "name": "connected",
            "baseName": "connected",
            "type": "boolean"
        },
        {
            "name": "admin",
            "baseName": "admin",
            "type": "boolean"
        },
        {
            "name": "moderator",
            "baseName": "moderator",
            "type": "boolean"
        },
        {
            "name": "banned",
            "baseName": "banned",
            "type": "boolean"
        },
        {
            "name": "inGarden",
            "baseName": "in_garden",
            "type": "boolean"
        },
        {
            "name": "verified",
            "baseName": "verified",
            "type": "boolean"
        },
        {
            "name": "wonSoloTournaments",
            "baseName": "won_solo_tournaments",
            "type": "number"
        },
        {
            "name": "wonFarmerTournaments",
            "baseName": "won_farmer_tournaments",
            "type": "number"
        },
        {
            "name": "wonTeamTournaments",
            "baseName": "won_team_tournaments",
            "type": "number"
        },
        {
            "name": "wonBattleRoyale",
            "baseName": "won_battle_royale",
            "type": "number"
        },
        {
            "name": "totalLevel",
            "baseName": "total_level",
            "type": "number"
        },
        {
            "name": "leekCount",
            "baseName": "leek_count",
            "type": "number"
        },
        {
            "name": "fights",
            "baseName": "fights",
            "type": "number"
        },
        {
            "name": "teamFights",
            "baseName": "team_fights",
            "type": "number"
        },
        {
            "name": "trophies",
            "baseName": "trophies",
            "type": "number"
        },
        {
            "name": "points",
            "baseName": "points",
            "type": "number"
        },
        {
            "name": "ranking",
            "baseName": "ranking",
            "type": "number"
        },
        {
            "name": "godsonsLevel",
            "baseName": "godsons_level",
            "type": "number"
        },
        {
            "name": "habs",
            "baseName": "habs",
            "type": "number"
        },
        {
            "name": "crystals",
            "baseName": "crystals",
            "type": "number"
        },
        {
            "name": "team",
            "baseName": "team",
            "type": "Team"
        },
        {
            "name": "weapons",
            "baseName": "weapons",
            "type": "Array<Item>"
        },
        {
            "name": "chips",
            "baseName": "chips",
            "type": "Array<Item>"
        },
        {
            "name": "potions",
            "baseName": "potions",
            "type": "Array<Item>"
        },
        {
            "name": "hats",
            "baseName": "hats",
            "type": "Array<Item>"
        },
        {
            "name": "resources",
            "baseName": "resources",
            "type": "Array<Item>"
        },
        {
            "name": "components",
            "baseName": "components",
            "type": "Array<Item>"
        },
        {
            "name": "schemes",
            "baseName": "schemes",
            "type": "Array<Item>"
        },
        {
            "name": "pomps",
            "baseName": "pomps",
            "type": "Array<Item>"
        },
        {
            "name": "leeks",
            "baseName": "leeks",
            "type": "{ [key: string]: Leek; }"
        },
        {
            "name": "leekAis",
            "baseName": "leek_ais",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "folders",
            "baseName": "folders",
            "type": "Array<Folder>"
        },
        {
            "name": "ais",
            "baseName": "ais",
            "type": "Array<Ia>"
        }
    ];
    static getAttributeTypeMap() {
        return Farmer.attributeTypeMap;
    }
}
exports.Farmer = Farmer;
