/**
 * Leekwars
 * Leekwars backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AiTree } from './aiTree';
import { Item } from './item';
import { Leek } from './leek';
import { Team } from './team';

/**
* Farmer
*/
export class Farmer {
    'id': number;
    'login': string;
    'name': string;
    'talent': number;
    'maxTalent': number;
    'talentMore': number;
    'victories': number;
    'draws': number;
    'defeats': number;
    'connected': boolean;
    'admin': boolean;
    'moderator': boolean;
    'banned': boolean;
    'verified': boolean;
    'wonSoloTournaments': number;
    'wonFarmerTournaments': number;
    'wonTeamTournaments': number;
    'wonBattleRoyale': number;
    'totalLevel': number;
    'leekCount': number;
    'inGarden': boolean;
    'fights': number;
    'boughtFight': number;
    'teamFights': number;
    'trophies': number;
    'points': number;
    'ranking': number;
    'habs': number;
    'crystals': number;
    'team': Team;
    /**
    * Weapons list
    */
    'weapons': Array<Item>;
    /**
    * Chips list
    */
    'chips': Array<Item>;
    /**
    * Potions list
    */
    'potions': Array<Item>;
    /**
    * Hats list
    */
    'hats': Array<Item>;
    /**
    * Resources list
    */
    'resources': Array<Item>;
    /**
    * Component list
    */
    'components': Array<Item>;
    /**
    * Component recipe list
    */
    'schemes': Array<Item>;
    /**
    * Some item list ???
    */
    'pomps': Array<Item>;
    /**
    * Leeks by id
    */
    'leeks': { [key: string]: Leek; };
    'aiTree': AiTree;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "login",
            "baseName": "login",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "talent",
            "baseName": "talent",
            "type": "number"
        },
        {
            "name": "maxTalent",
            "baseName": "max_talent",
            "type": "number"
        },
        {
            "name": "talentMore",
            "baseName": "talent_more",
            "type": "number"
        },
        {
            "name": "victories",
            "baseName": "victories",
            "type": "number"
        },
        {
            "name": "draws",
            "baseName": "draws",
            "type": "number"
        },
        {
            "name": "defeats",
            "baseName": "defeats",
            "type": "number"
        },
        {
            "name": "connected",
            "baseName": "connected",
            "type": "boolean"
        },
        {
            "name": "admin",
            "baseName": "admin",
            "type": "boolean"
        },
        {
            "name": "moderator",
            "baseName": "moderator",
            "type": "boolean"
        },
        {
            "name": "banned",
            "baseName": "banned",
            "type": "boolean"
        },
        {
            "name": "verified",
            "baseName": "verified",
            "type": "boolean"
        },
        {
            "name": "wonSoloTournaments",
            "baseName": "won_solo_tournaments",
            "type": "number"
        },
        {
            "name": "wonFarmerTournaments",
            "baseName": "won_farmer_tournaments",
            "type": "number"
        },
        {
            "name": "wonTeamTournaments",
            "baseName": "won_team_tournaments",
            "type": "number"
        },
        {
            "name": "wonBattleRoyale",
            "baseName": "won_battle_royale",
            "type": "number"
        },
        {
            "name": "totalLevel",
            "baseName": "total_level",
            "type": "number"
        },
        {
            "name": "leekCount",
            "baseName": "leek_count",
            "type": "number"
        },
        {
            "name": "inGarden",
            "baseName": "in_garden",
            "type": "boolean"
        },
        {
            "name": "fights",
            "baseName": "fights",
            "type": "number"
        },
        {
            "name": "boughtFight",
            "baseName": "bought_fight",
            "type": "number"
        },
        {
            "name": "teamFights",
            "baseName": "team_fights",
            "type": "number"
        },
        {
            "name": "trophies",
            "baseName": "trophies",
            "type": "number"
        },
        {
            "name": "points",
            "baseName": "points",
            "type": "number"
        },
        {
            "name": "ranking",
            "baseName": "ranking",
            "type": "number"
        },
        {
            "name": "habs",
            "baseName": "habs",
            "type": "number"
        },
        {
            "name": "crystals",
            "baseName": "crystals",
            "type": "number"
        },
        {
            "name": "team",
            "baseName": "team",
            "type": "Team"
        },
        {
            "name": "weapons",
            "baseName": "weapons",
            "type": "Array<Item>"
        },
        {
            "name": "chips",
            "baseName": "chips",
            "type": "Array<Item>"
        },
        {
            "name": "potions",
            "baseName": "potions",
            "type": "Array<Item>"
        },
        {
            "name": "hats",
            "baseName": "hats",
            "type": "Array<Item>"
        },
        {
            "name": "resources",
            "baseName": "resources",
            "type": "Array<Item>"
        },
        {
            "name": "components",
            "baseName": "components",
            "type": "Array<Item>"
        },
        {
            "name": "schemes",
            "baseName": "schemes",
            "type": "Array<Item>"
        },
        {
            "name": "pomps",
            "baseName": "pomps",
            "type": "Array<Item>"
        },
        {
            "name": "leeks",
            "baseName": "leeks",
            "type": "{ [key: string]: Leek; }"
        },
        {
            "name": "aiTree",
            "baseName": "ai_tree",
            "type": "AiTree"
        }    ];

    static getAttributeTypeMap() {
        return Farmer.attributeTypeMap;
    }
}

