/**
 * Leekwars
 * Leekwars backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FightResumeLeeks1Inner } from './fightResumeLeeks1Inner';

/**
* TODO
*/
export class FightResume {
    /**
    * Fight id
    */
    'id': number;
    'leeks1': Array<FightResumeLeeks1Inner>;
    'leeks2': Array<FightResumeLeeks1Inner>;
    /**
    * Winner side
    */
    'winner': number;
    /**
    * Fight status (2  = finished)
    */
    'status': number;
    /**
    * Fight date
    */
    'date': number;
    /**
    * Context type
    */
    'context': number;
    /**
    * Fight type
    */
    'type'?: number;
    /**
    * Fight farmer1
    */
    'farmer1': number;
    /**
    * Fight farmer2
    */
    'farmer2': number;
    /**
    * Fight team1
    */
    'team1': number;
    /**
    * Fight team2
    */
    'team2': number;
    /**
    * Fight chests
    */
    'chests': number;
    /**
    * Fight comments
    */
    'comments': number;
    /**
    * Fight unlocked trophies
    */
    'trophies': number;
    /**
    * Fight level up
    */
    'levelups': number;
    /**
    * Fight rare loot
    */
    'rareloot': number;
    /**
    * Fight result
    */
    'result': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "leeks1",
            "baseName": "leeks1",
            "type": "Array<FightResumeLeeks1Inner>"
        },
        {
            "name": "leeks2",
            "baseName": "leeks2",
            "type": "Array<FightResumeLeeks1Inner>"
        },
        {
            "name": "winner",
            "baseName": "winner",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "number"
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "number"
        },
        {
            "name": "context",
            "baseName": "context",
            "type": "number"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "number"
        },
        {
            "name": "farmer1",
            "baseName": "farmer1",
            "type": "number"
        },
        {
            "name": "farmer2",
            "baseName": "farmer2",
            "type": "number"
        },
        {
            "name": "team1",
            "baseName": "team1",
            "type": "number"
        },
        {
            "name": "team2",
            "baseName": "team2",
            "type": "number"
        },
        {
            "name": "chests",
            "baseName": "chests",
            "type": "number"
        },
        {
            "name": "comments",
            "baseName": "comments",
            "type": "number"
        },
        {
            "name": "trophies",
            "baseName": "trophies",
            "type": "number"
        },
        {
            "name": "levelups",
            "baseName": "levelups",
            "type": "number"
        },
        {
            "name": "rareloot",
            "baseName": "rareloot",
            "type": "number"
        },
        {
            "name": "result",
            "baseName": "result",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return FightResume.attributeTypeMap;
    }
}

