"use strict";
/**
 * Leekwars
 * Leekwars backend api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GardenGardenMyTeam = void 0;
/**
* Summary info about the user\'s team
*/
class GardenGardenMyTeam {
    'id';
    'name';
    'level';
    'emblemChanged';
    static discriminator = undefined;
    static attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "number"
        },
        {
            "name": "emblemChanged",
            "baseName": "emblem_changed",
            "type": "number"
        }
    ];
    static getAttributeTypeMap() {
        return GardenGardenMyTeam.attributeTypeMap;
    }
}
exports.GardenGardenMyTeam = GardenGardenMyTeam;
