/**
 * Leekwars
 * Leekwars backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GardenGardenMyCompositionsInner {
    'id': number;
    'teamId': number;
    /**
    * Composition name
    */
    'name': string;
    'teamName': string;
    'level': number;
    'totalLevel': number;
    'talent': number;
    'fights': number;
    'emblemChanged': number;
    'leekCount': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "teamId",
            "baseName": "team_id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "teamName",
            "baseName": "team_name",
            "type": "string"
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "number"
        },
        {
            "name": "totalLevel",
            "baseName": "total_level",
            "type": "number"
        },
        {
            "name": "talent",
            "baseName": "talent",
            "type": "number"
        },
        {
            "name": "fights",
            "baseName": "fights",
            "type": "number"
        },
        {
            "name": "emblemChanged",
            "baseName": "emblem_changed",
            "type": "number"
        },
        {
            "name": "leekCount",
            "baseName": "leek_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return GardenGardenMyCompositionsInner.attributeTypeMap;
    }
}

