"use strict";
/**
 * Leekwars
 * Leekwars backend api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Garden = void 0;
/**
* Garden informations
*/
class Garden {
    'garden';
    static discriminator = undefined;
    static attributeTypeMap = [
        {
            "name": "garden",
            "baseName": "garden",
            "type": "GardenGarden"
        }
    ];
    static getAttributeTypeMap() {
        return Garden.attributeTypeMap;
    }
}
exports.Garden = Garden;
