"use strict";
/**
 * Leekwars
 * Leekwars backend api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GardenGarden = void 0;
/**
* Garden payload
*/
class GardenGarden {
    /**
    * Number of fights used
    */
    'fights';
    /**
    * Maximum allowed fights
    */
    'maxFights';
    'farmerEnabled';
    'teamEnabled';
    /**
    * List of the user\'s compositions
    */
    'myCompositions';
    'myTeam';
    'totalSoloFights';
    'maxSoloFights';
    'teamFights';
    'maxTeamFights';
    'battleRoyaleFights';
    'maxBattleRoyaleFights';
    'battleRoyaleEnabled';
    static discriminator = undefined;
    static attributeTypeMap = [
        {
            "name": "fights",
            "baseName": "fights",
            "type": "number"
        },
        {
            "name": "maxFights",
            "baseName": "max_fights",
            "type": "number"
        },
        {
            "name": "farmerEnabled",
            "baseName": "farmer_enabled",
            "type": "boolean"
        },
        {
            "name": "teamEnabled",
            "baseName": "team_enabled",
            "type": "boolean"
        },
        {
            "name": "myCompositions",
            "baseName": "my_compositions",
            "type": "Array<GardenGardenMyCompositionsInner>"
        },
        {
            "name": "myTeam",
            "baseName": "my_team",
            "type": "GardenGardenMyTeam"
        },
        {
            "name": "totalSoloFights",
            "baseName": "total_solo_fights",
            "type": "number"
        },
        {
            "name": "maxSoloFights",
            "baseName": "max_solo_fights",
            "type": "number"
        },
        {
            "name": "teamFights",
            "baseName": "team_fights",
            "type": "number"
        },
        {
            "name": "maxTeamFights",
            "baseName": "max_team_fights",
            "type": "number"
        },
        {
            "name": "battleRoyaleFights",
            "baseName": "battle_royale_fights",
            "type": "number"
        },
        {
            "name": "maxBattleRoyaleFights",
            "baseName": "max_battle_royale_fights",
            "type": "number"
        },
        {
            "name": "battleRoyaleEnabled",
            "baseName": "battle_royale_enabled",
            "type": "boolean"
        }
    ];
    static getAttributeTypeMap() {
        return GardenGarden.attributeTypeMap;
    }
}
exports.GardenGarden = GardenGarden;
