/**
 * Leekwars
 * Leekwars backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GardenGardenMyCompositionsInner } from './gardenGardenMyCompositionsInner';
import { GardenGardenMyTeam } from './gardenGardenMyTeam';

/**
* Garden payload
*/
export class GardenGarden {
    /**
    * Number of fights used
    */
    'fights': number;
    /**
    * Maximum allowed fights
    */
    'maxFights': number;
    'farmerEnabled': boolean;
    'teamEnabled': boolean;
    /**
    * List of the user\'s compositions
    */
    'myCompositions': Array<GardenGardenMyCompositionsInner>;
    'myTeam': GardenGardenMyTeam;
    'totalSoloFights': number;
    'maxSoloFights': number;
    'teamFights': number;
    'maxTeamFights': number;
    'battleRoyaleFights': number;
    'maxBattleRoyaleFights': number;
    'battleRoyaleEnabled': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fights",
            "baseName": "fights",
            "type": "number"
        },
        {
            "name": "maxFights",
            "baseName": "max_fights",
            "type": "number"
        },
        {
            "name": "farmerEnabled",
            "baseName": "farmer_enabled",
            "type": "boolean"
        },
        {
            "name": "teamEnabled",
            "baseName": "team_enabled",
            "type": "boolean"
        },
        {
            "name": "myCompositions",
            "baseName": "my_compositions",
            "type": "Array<GardenGardenMyCompositionsInner>"
        },
        {
            "name": "myTeam",
            "baseName": "my_team",
            "type": "GardenGardenMyTeam"
        },
        {
            "name": "totalSoloFights",
            "baseName": "total_solo_fights",
            "type": "number"
        },
        {
            "name": "maxSoloFights",
            "baseName": "max_solo_fights",
            "type": "number"
        },
        {
            "name": "teamFights",
            "baseName": "team_fights",
            "type": "number"
        },
        {
            "name": "maxTeamFights",
            "baseName": "max_team_fights",
            "type": "number"
        },
        {
            "name": "battleRoyaleFights",
            "baseName": "battle_royale_fights",
            "type": "number"
        },
        {
            "name": "maxBattleRoyaleFights",
            "baseName": "max_battle_royale_fights",
            "type": "number"
        },
        {
            "name": "battleRoyaleEnabled",
            "baseName": "battle_royale_enabled",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return GardenGarden.attributeTypeMap;
    }
}

