"use strict";
/**
 * Leekwars
 * Leekwars backend api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Ia = void 0;
/**
* IA file
*/
class Ia {
    'id';
    'name';
    'valid';
    'folder';
    'version';
    'strict';
    'totalLines';
    'totalChars';
    'entrypoint';
    static discriminator = undefined;
    static attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "valid",
            "baseName": "valid",
            "type": "boolean"
        },
        {
            "name": "folder",
            "baseName": "folder",
            "type": "number"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "number"
        },
        {
            "name": "strict",
            "baseName": "strict",
            "type": "boolean"
        },
        {
            "name": "totalLines",
            "baseName": "total_lines",
            "type": "number"
        },
        {
            "name": "totalChars",
            "baseName": "total_chars",
            "type": "number"
        },
        {
            "name": "entrypoint",
            "baseName": "entrypoint",
            "type": "boolean"
        }
    ];
    static getAttributeTypeMap() {
        return Ia.attributeTypeMap;
    }
}
exports.Ia = Ia;
