/**
 * Leekwars
 * Leekwars backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* IA file
*/
export class Ia {
    'id': number;
    'name': string;
    'valid': boolean;
    'folder': number;
    'version': number;
    'strict': boolean;
    'totalLines': number;
    'totalChars': number;
    'entrypoint': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "valid",
            "baseName": "valid",
            "type": "boolean"
        },
        {
            "name": "folder",
            "baseName": "folder",
            "type": "number"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "number"
        },
        {
            "name": "strict",
            "baseName": "strict",
            "type": "boolean"
        },
        {
            "name": "totalLines",
            "baseName": "total_lines",
            "type": "number"
        },
        {
            "name": "totalChars",
            "baseName": "total_chars",
            "type": "number"
        },
        {
            "name": "entrypoint",
            "baseName": "entrypoint",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return Ia.attributeTypeMap;
    }
}

