"use strict";
/**
 * Leekwars
 * Leekwars backend api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Leek = void 0;
/**
* Leek characteristics
*/
class Leek {
    /**
    * Unique character identifier
    */
    'id';
    /**
    * Character name
    */
    'name';
    /**
    * ???
    */
    'capital';
    /**
    * Leek level
    */
    'level';
    /**
    * Talent points
    */
    'talent';
    /**
    * Skin id
    */
    'skin';
    /**
    * Hat id (nullable if none)
    */
    'hat';
    /**
    * leekscript id
    */
    'ai';
    /**
    * Displayed weapon id (cosmetic perk)
    */
    'weapon';
    /**
    * List of titles
    */
    'title';
    /**
    * Metallic cosmetic perk
    */
    'metal';
    /**
    * Face variant id (0 neutral, 1 happy, other not documented yet)
    */
    'face';
    /**
    * Base life
    */
    'life';
    /**
    * Base strength
    */
    'strength';
    /**
    * Base wisdom
    */
    'wisdom';
    /**
    * Base agility
    */
    'agility';
    /**
    * Base resistance
    */
    'resistance';
    /**
    * Base science
    */
    'science';
    /**
    * Base magic
    */
    'magic';
    /**
    * Base frequency
    */
    'frequency';
    /**
    * Number of cores
    */
    'cores';
    /**
    * RAM value
    */
    'ram';
    /**
    * TP stat
    */
    'tp';
    /**
    * MP stat
    */
    'mp';
    /**
    * Total life with components
    */
    'totalLife';
    /**
    * Total strength with components
    */
    'totalStrength';
    /**
    * Total wisdom with components
    */
    'totalWisdom';
    /**
    * Total agility with components
    */
    'totalAgility';
    /**
    * Total resistance with components
    */
    'totalResistance';
    /**
    * Total science with components
    */
    'totalScience';
    /**
    * Total magic with components
    */
    'totalMagic';
    /**
    * Total frequency with components
    */
    'totalFrequency';
    /**
    * Total cores with components
    */
    'totalCores';
    /**
    * Total RAM with components
    */
    'totalRam';
    /**
    * Total TP with components
    */
    'totalTp';
    /**
    * Total MP with components
    */
    'totalMp';
    static discriminator = undefined;
    static attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "capital",
            "baseName": "capital",
            "type": "number"
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "number"
        },
        {
            "name": "talent",
            "baseName": "talent",
            "type": "number"
        },
        {
            "name": "skin",
            "baseName": "skin",
            "type": "number"
        },
        {
            "name": "hat",
            "baseName": "hat",
            "type": "number"
        },
        {
            "name": "ai",
            "baseName": "ai",
            "type": "number"
        },
        {
            "name": "weapon",
            "baseName": "weapon",
            "type": "number"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "Array<string>"
        },
        {
            "name": "metal",
            "baseName": "metal",
            "type": "boolean"
        },
        {
            "name": "face",
            "baseName": "face",
            "type": "number"
        },
        {
            "name": "life",
            "baseName": "life",
            "type": "number"
        },
        {
            "name": "strength",
            "baseName": "strength",
            "type": "number"
        },
        {
            "name": "wisdom",
            "baseName": "wisdom",
            "type": "number"
        },
        {
            "name": "agility",
            "baseName": "agility",
            "type": "number"
        },
        {
            "name": "resistance",
            "baseName": "resistance",
            "type": "number"
        },
        {
            "name": "science",
            "baseName": "science",
            "type": "number"
        },
        {
            "name": "magic",
            "baseName": "magic",
            "type": "number"
        },
        {
            "name": "frequency",
            "baseName": "frequency",
            "type": "number"
        },
        {
            "name": "cores",
            "baseName": "cores",
            "type": "number"
        },
        {
            "name": "ram",
            "baseName": "ram",
            "type": "number"
        },
        {
            "name": "tp",
            "baseName": "tp",
            "type": "number"
        },
        {
            "name": "mp",
            "baseName": "mp",
            "type": "number"
        },
        {
            "name": "totalLife",
            "baseName": "total_life",
            "type": "number"
        },
        {
            "name": "totalStrength",
            "baseName": "total_strength",
            "type": "number"
        },
        {
            "name": "totalWisdom",
            "baseName": "total_wisdom",
            "type": "number"
        },
        {
            "name": "totalAgility",
            "baseName": "total_agility",
            "type": "number"
        },
        {
            "name": "totalResistance",
            "baseName": "total_resistance",
            "type": "number"
        },
        {
            "name": "totalScience",
            "baseName": "total_science",
            "type": "number"
        },
        {
            "name": "totalMagic",
            "baseName": "total_magic",
            "type": "number"
        },
        {
            "name": "totalFrequency",
            "baseName": "total_frequency",
            "type": "number"
        },
        {
            "name": "totalCores",
            "baseName": "total_cores",
            "type": "number"
        },
        {
            "name": "totalRam",
            "baseName": "total_ram",
            "type": "number"
        },
        {
            "name": "totalTp",
            "baseName": "total_tp",
            "type": "number"
        },
        {
            "name": "totalMp",
            "baseName": "total_mp",
            "type": "number"
        }
    ];
    static getAttributeTypeMap() {
        return Leek.attributeTypeMap;
    }
}
exports.Leek = Leek;
