/**
 * Leekwars
 * Leekwars backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Leek characteristics
*/
export class Leek {
    /**
    * Unique character identifier
    */
    'id': number;
    /**
    * Character name
    */
    'name': string;
    /**
    * ???
    */
    'capital': number;
    /**
    * Leek level
    */
    'level': number;
    /**
    * Talent points
    */
    'talent': number;
    /**
    * Skin id
    */
    'skin': number;
    /**
    * Hat id (nullable if none)
    */
    'hat'?: number;
    /**
    * leekscript id
    */
    'ai': number;
    /**
    * Displayed weapon id (cosmetic perk)
    */
    'weapon'?: number;
    /**
    * List of titles
    */
    'title': Array<string>;
    /**
    * Metallic cosmetic perk
    */
    'metal': boolean;
    /**
    * Face variant id (0 neutral, 1 happy, other not documented yet)
    */
    'face': number;
    /**
    * Base life
    */
    'life': number;
    /**
    * Base strength
    */
    'strength': number;
    /**
    * Base wisdom
    */
    'wisdom': number;
    /**
    * Base agility
    */
    'agility': number;
    /**
    * Base resistance
    */
    'resistance': number;
    /**
    * Base science
    */
    'science': number;
    /**
    * Base magic
    */
    'magic': number;
    /**
    * Base frequency
    */
    'frequency': number;
    /**
    * Number of cores
    */
    'cores': number;
    /**
    * RAM value
    */
    'ram': number;
    /**
    * TP stat
    */
    'tp': number;
    /**
    * MP stat
    */
    'mp': number;
    /**
    * Total life with components
    */
    'totalLife': number;
    /**
    * Total strength with components
    */
    'totalStrength': number;
    /**
    * Total wisdom with components
    */
    'totalWisdom': number;
    /**
    * Total agility with components
    */
    'totalAgility': number;
    /**
    * Total resistance with components
    */
    'totalResistance': number;
    /**
    * Total science with components
    */
    'totalScience': number;
    /**
    * Total magic with components
    */
    'totalMagic': number;
    /**
    * Total frequency with components
    */
    'totalFrequency': number;
    /**
    * Total cores with components
    */
    'totalCores': number;
    /**
    * Total RAM with components
    */
    'totalRam': number;
    /**
    * Total TP with components
    */
    'totalTp': number;
    /**
    * Total MP with components
    */
    'totalMp': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "capital",
            "baseName": "capital",
            "type": "number"
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "number"
        },
        {
            "name": "talent",
            "baseName": "talent",
            "type": "number"
        },
        {
            "name": "skin",
            "baseName": "skin",
            "type": "number"
        },
        {
            "name": "hat",
            "baseName": "hat",
            "type": "number"
        },
        {
            "name": "ai",
            "baseName": "ai",
            "type": "number"
        },
        {
            "name": "weapon",
            "baseName": "weapon",
            "type": "number"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "Array<string>"
        },
        {
            "name": "metal",
            "baseName": "metal",
            "type": "boolean"
        },
        {
            "name": "face",
            "baseName": "face",
            "type": "number"
        },
        {
            "name": "life",
            "baseName": "life",
            "type": "number"
        },
        {
            "name": "strength",
            "baseName": "strength",
            "type": "number"
        },
        {
            "name": "wisdom",
            "baseName": "wisdom",
            "type": "number"
        },
        {
            "name": "agility",
            "baseName": "agility",
            "type": "number"
        },
        {
            "name": "resistance",
            "baseName": "resistance",
            "type": "number"
        },
        {
            "name": "science",
            "baseName": "science",
            "type": "number"
        },
        {
            "name": "magic",
            "baseName": "magic",
            "type": "number"
        },
        {
            "name": "frequency",
            "baseName": "frequency",
            "type": "number"
        },
        {
            "name": "cores",
            "baseName": "cores",
            "type": "number"
        },
        {
            "name": "ram",
            "baseName": "ram",
            "type": "number"
        },
        {
            "name": "tp",
            "baseName": "tp",
            "type": "number"
        },
        {
            "name": "mp",
            "baseName": "mp",
            "type": "number"
        },
        {
            "name": "totalLife",
            "baseName": "total_life",
            "type": "number"
        },
        {
            "name": "totalStrength",
            "baseName": "total_strength",
            "type": "number"
        },
        {
            "name": "totalWisdom",
            "baseName": "total_wisdom",
            "type": "number"
        },
        {
            "name": "totalAgility",
            "baseName": "total_agility",
            "type": "number"
        },
        {
            "name": "totalResistance",
            "baseName": "total_resistance",
            "type": "number"
        },
        {
            "name": "totalScience",
            "baseName": "total_science",
            "type": "number"
        },
        {
            "name": "totalMagic",
            "baseName": "total_magic",
            "type": "number"
        },
        {
            "name": "totalFrequency",
            "baseName": "total_frequency",
            "type": "number"
        },
        {
            "name": "totalCores",
            "baseName": "total_cores",
            "type": "number"
        },
        {
            "name": "totalRam",
            "baseName": "total_ram",
            "type": "number"
        },
        {
            "name": "totalTp",
            "baseName": "total_tp",
            "type": "number"
        },
        {
            "name": "totalMp",
            "baseName": "total_mp",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Leek.attributeTypeMap;
    }
}

