/**
 * Leekwars
 * Leekwars backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Farmer } from './farmer';

/**
* Login big dump with a lot of informations
*/
export class Logindump {
    'farmer': Farmer;
    /**
    * Connected farmers
    */
    'farmers': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "farmer",
            "baseName": "farmer",
            "type": "Farmer"
        },
        {
            "name": "farmers",
            "baseName": "farmers",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Logindump.attributeTypeMap;
    }
}

