"use strict";
/**
 * Leekwars
 * Leekwars backend api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Logindump = void 0;
/**
* Login big dump with a lot of informations
*/
class Logindump {
    'farmer';
    /**
    * Connected farmers
    */
    'farmers';
    static discriminator = undefined;
    static attributeTypeMap = [
        {
            "name": "farmer",
            "baseName": "farmer",
            "type": "Farmer"
        },
        {
            "name": "farmers",
            "baseName": "farmers",
            "type": "number"
        }
    ];
    static getAttributeTypeMap() {
        return Logindump.attributeTypeMap;
    }
}
exports.Logindump = Logindump;
