/**
 * Leekwars
 * Leekwars backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FightResume } from './fightResume';
import { PublicLeekAi } from './publicLeekAi';
import { PublicLeekChipsInner } from './publicLeekChipsInner';
import { TournamentResume } from './tournamentResume';

/**
* Leek public characteristics
*/
export class PublicLeek {
    /**
    * Unique character identifier
    */
    'id': number;
    /**
    * Character name
    */
    'name': string;
    /**
    * Talent points
    */
    'talent': number;
    /**
    * Talent points above average
    */
    'talentMore': number;
    /**
    * Leek level
    */
    'level': number;
    /**
    * Leek xp
    */
    'xp': number;
    /**
    * Total xp required for next level
    */
    'upXp': number;
    /**
    * Total xp from previous level
    */
    'downXp': number;
    /**
    * Remaining xp needed to level up
    */
    'remainingXp': number;
    /**
    * Is xp locked
    */
    'xpBlocked': boolean;
    /**
    * Skin id
    */
    'skin': number;
    /**
    * Hat id (nullable if none)
    */
    'hat'?: number;
    /**
    * List of titles
    */
    'title': Array<string>;
    /**
    * Metallic cosmetic perk
    */
    'metal': boolean;
    /**
    * Face variant id (0 neutral, 1 happy, other not documented yet)
    */
    'face': number;
    /**
    * Base life
    */
    'life': number;
    /**
    * Base strength
    */
    'strength': number;
    /**
    * Base wisdom
    */
    'wisdom': number;
    /**
    * Base agility
    */
    'agility': number;
    /**
    * Base resistance
    */
    'resistance': number;
    /**
    * Base science
    */
    'science': number;
    /**
    * Base magic
    */
    'magic': number;
    /**
    * Base frequency
    */
    'frequency': number;
    /**
    * Number of cores
    */
    'cores': number;
    /**
    * RAM value
    */
    'ram': number;
    /**
    * TP stat
    */
    'tp': number;
    /**
    * MP stat
    */
    'mp': number;
    /**
    * Total life with components
    */
    'totalLife': number;
    /**
    * Total strength with components
    */
    'totalStrength': number;
    /**
    * Total wisdom with components
    */
    'totalWisdom': number;
    /**
    * Total agility with components
    */
    'totalAgility': number;
    /**
    * Total resistance with components
    */
    'totalResistance': number;
    /**
    * Total science with components
    */
    'totalScience': number;
    /**
    * Total magic with components
    */
    'totalMagic': number;
    /**
    * Total frequency with components
    */
    'totalFrequency': number;
    /**
    * Total cores with components
    */
    'totalCores': number;
    /**
    * Total RAM with components
    */
    'totalRam': number;
    /**
    * Total TP with components
    */
    'totalTp': number;
    /**
    * Total MP with components
    */
    'totalMp': number;
    /**
    * Displayed weapon id (cosmetic perk)
    */
    'weapon'?: number;
    /**
    * Victory count
    */
    'victories': number;
    /**
    * Draw count
    */
    'draws': number;
    /**
    * Defeat count
    */
    'defeats': number;
    /**
    * Victory/Defeat ratio
    */
    'ratio': number;
    /**
    * Chips equipped
    */
    'chips': Array<PublicLeekChipsInner>;
    /**
    * Weapon equipped
    */
    'weapons': Array<PublicLeekChipsInner>;
    'ai': PublicLeekAi;
    'maxWeapons': number;
    'maxChips': number;
    'inGarden': boolean;
    'ranking': number;
    'talentHistory': Array<number>;
    'fights': Array<FightResume>;
    'tournaments': Array<TournamentResume>;
    'components': Array<PublicLeekChipsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "talent",
            "baseName": "talent",
            "type": "number"
        },
        {
            "name": "talentMore",
            "baseName": "talent_more",
            "type": "number"
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "number"
        },
        {
            "name": "xp",
            "baseName": "xp",
            "type": "number"
        },
        {
            "name": "upXp",
            "baseName": "up_xp",
            "type": "number"
        },
        {
            "name": "downXp",
            "baseName": "down_xp",
            "type": "number"
        },
        {
            "name": "remainingXp",
            "baseName": "remaining_xp",
            "type": "number"
        },
        {
            "name": "xpBlocked",
            "baseName": "xp_blocked",
            "type": "boolean"
        },
        {
            "name": "skin",
            "baseName": "skin",
            "type": "number"
        },
        {
            "name": "hat",
            "baseName": "hat",
            "type": "number"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "Array<string>"
        },
        {
            "name": "metal",
            "baseName": "metal",
            "type": "boolean"
        },
        {
            "name": "face",
            "baseName": "face",
            "type": "number"
        },
        {
            "name": "life",
            "baseName": "life",
            "type": "number"
        },
        {
            "name": "strength",
            "baseName": "strength",
            "type": "number"
        },
        {
            "name": "wisdom",
            "baseName": "wisdom",
            "type": "number"
        },
        {
            "name": "agility",
            "baseName": "agility",
            "type": "number"
        },
        {
            "name": "resistance",
            "baseName": "resistance",
            "type": "number"
        },
        {
            "name": "science",
            "baseName": "science",
            "type": "number"
        },
        {
            "name": "magic",
            "baseName": "magic",
            "type": "number"
        },
        {
            "name": "frequency",
            "baseName": "frequency",
            "type": "number"
        },
        {
            "name": "cores",
            "baseName": "cores",
            "type": "number"
        },
        {
            "name": "ram",
            "baseName": "ram",
            "type": "number"
        },
        {
            "name": "tp",
            "baseName": "tp",
            "type": "number"
        },
        {
            "name": "mp",
            "baseName": "mp",
            "type": "number"
        },
        {
            "name": "totalLife",
            "baseName": "total_life",
            "type": "number"
        },
        {
            "name": "totalStrength",
            "baseName": "total_strength",
            "type": "number"
        },
        {
            "name": "totalWisdom",
            "baseName": "total_wisdom",
            "type": "number"
        },
        {
            "name": "totalAgility",
            "baseName": "total_agility",
            "type": "number"
        },
        {
            "name": "totalResistance",
            "baseName": "total_resistance",
            "type": "number"
        },
        {
            "name": "totalScience",
            "baseName": "total_science",
            "type": "number"
        },
        {
            "name": "totalMagic",
            "baseName": "total_magic",
            "type": "number"
        },
        {
            "name": "totalFrequency",
            "baseName": "total_frequency",
            "type": "number"
        },
        {
            "name": "totalCores",
            "baseName": "total_cores",
            "type": "number"
        },
        {
            "name": "totalRam",
            "baseName": "total_ram",
            "type": "number"
        },
        {
            "name": "totalTp",
            "baseName": "total_tp",
            "type": "number"
        },
        {
            "name": "totalMp",
            "baseName": "total_mp",
            "type": "number"
        },
        {
            "name": "weapon",
            "baseName": "weapon",
            "type": "number"
        },
        {
            "name": "victories",
            "baseName": "victories",
            "type": "number"
        },
        {
            "name": "draws",
            "baseName": "draws",
            "type": "number"
        },
        {
            "name": "defeats",
            "baseName": "defeats",
            "type": "number"
        },
        {
            "name": "ratio",
            "baseName": "ratio",
            "type": "number"
        },
        {
            "name": "chips",
            "baseName": "chips",
            "type": "Array<PublicLeekChipsInner>"
        },
        {
            "name": "weapons",
            "baseName": "weapons",
            "type": "Array<PublicLeekChipsInner>"
        },
        {
            "name": "ai",
            "baseName": "ai",
            "type": "PublicLeekAi"
        },
        {
            "name": "maxWeapons",
            "baseName": "max_weapons",
            "type": "number"
        },
        {
            "name": "maxChips",
            "baseName": "max_chips",
            "type": "number"
        },
        {
            "name": "inGarden",
            "baseName": "in_garden",
            "type": "boolean"
        },
        {
            "name": "ranking",
            "baseName": "ranking",
            "type": "number"
        },
        {
            "name": "talentHistory",
            "baseName": "talent_history",
            "type": "Array<number>"
        },
        {
            "name": "fights",
            "baseName": "fights",
            "type": "Array<FightResume>"
        },
        {
            "name": "tournaments",
            "baseName": "tournaments",
            "type": "Array<TournamentResume>"
        },
        {
            "name": "components",
            "baseName": "components",
            "type": "Array<PublicLeekChipsInner>"
        }    ];

    static getAttributeTypeMap() {
        return PublicLeek.attributeTypeMap;
    }
}

