/**
 * Leekwars
 * Leekwars backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Team
*/
export class Team {
    'id': number;
    'name': string;
    'level': number;
    'emblemChanged': boolean;
    'chat': number;
    'memberLevel': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "number"
        },
        {
            "name": "emblemChanged",
            "baseName": "emblem_changed",
            "type": "boolean"
        },
        {
            "name": "chat",
            "baseName": "chat",
            "type": "number"
        },
        {
            "name": "memberLevel",
            "baseName": "member_level",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Team.attributeTypeMap;
    }
}

