/**
 * Leekwars
 * Leekwars backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Tournament resume
*/
export class TournamentResume {
    'id'?: number;
    'date'?: number;
    /**
    * Rounds by id
    */
    'rounds'?: { [key: string]: Array<number>; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "number"
        },
        {
            "name": "rounds",
            "baseName": "rounds",
            "type": "{ [key: string]: Array<number>; }"
        }    ];

    static getAttributeTypeMap() {
        return TournamentResume.attributeTypeMap;
    }
}

