name: Publish to npm
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Run in dry mode (no publish)'
        required: false
        default: 'false'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org/'
      - run: npm install
      - run: npm run build
      - name: Dry Run
        if: github.event.inputs.dry-run == 'true'
        run: echo Dry run, not publishing to npm.
      - name: Publish
        if: github.event.inputs.dry-run != 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
